
exports.seed = function(knex, Promise) {
  return knex('domains').del()
    .then(function () {
      return knex('domains').insert([
        {id: 1, name: 'Air'},
        {id: 2, name: 'Animal'},
        {id: 3, name: 'Arcana'},
        {id: 4, name: 'Balance'},
        {id: 5, name: 'Bestial'},
        {id: 6, name: 'Blightbringer'},
        {id: 7, name: 'Cavern'},
        {id: 8, name: 'Celestial'},
        {id: 9, name: 'Change'},
        {id: 10, name: 'Chaos'},
        {id: 11, name: 'Charm'},
        {id: 12, name: 'Civilization'},
        {id: 13, name: 'Cold'},
        {id: 14, name: 'Community'},
        {id: 15, name: 'Corruption'},
        {id: 16, name: 'Craft'},
        {id: 17, name: 'Creation'},
        {id: 18, name: 'Darkness'},
        {id: 19, name: 'Death'},
        {id: 20, name: 'Demonic'},
        {id: 21, name: 'Destruction'},
        {id: 22, name: 'Diabolic'},
        {id: 23, name: 'Divine'},
        {id: 24, name: 'Drow'},
        {id: 25, name: 'Dwarf'},
        {id: 26, name: 'Earth'},
        {id: 27, name: 'Elf'},
        {id: 28, name: 'Endurance'},
        {id: 29, name: 'Evil'},
        {id: 30, name: 'Family'},
        {id: 31, name: 'Fate'},
        {id: 32, name: 'Fey'},
        {id: 33, name: 'Fire'},
        {id: 34, name: 'Forge'},
        {id: 35, name: 'Freedom'},
        {id: 36, name: 'Glory'},
        {id: 37, name: 'Gnome'},
        {id: 38, name: 'Good'},
        {id: 39, name: 'Grave'},
        {id: 40, name: 'Greed'},
        {id: 41, name: 'Halfling'},
        {id: 42, name: 'Hatred'},
        {id: 43, name: 'Healing'},
        {id: 44, name: 'Herald'},
        {id: 45, name: 'Hope'},
        {id: 46, name: 'Illusion'},
        {id: 47, name: 'Joy'},
        {id: 48, name: 'Justice'},
        {id: 49, name: 'Knowledge'},
        {id: 50, name: 'Law'},
        {id: 51, name: 'Life'},
        {id: 52, name: 'Light'},
        {id: 53, name: 'Love'},
        {id: 54, name: 'Luck'},
        {id: 55, name: 'Madness'},
        {id: 56, name: 'Magic'},
        {id: 57, name: 'Mentalism'},
        {id: 58, name: 'Metal'},
        {id: 59, name: 'Mind'},
        {id: 60, name: 'Moon'},
        {id: 61, name: 'Nature'},
        {id: 62, name: 'Nobility'},
        {id: 63, name: 'Ocean'},
        {id: 64, name: 'Orc'},
        {id: 65, name: 'Pain'},
        {id: 66, name: 'Planning'},
        {id: 67, name: 'Plant'},
        {id: 68, name: 'Pleasure'},
        {id: 69, name: 'Poison'},
        {id: 70, name: 'Portal'},
        {id: 71, name: 'Protection'},
        {id: 72, name: 'Renewal'},
        {id: 73, name: 'Repose'},
        {id: 74, name: 'Retribution'},
        {id: 75, name: 'Rune'},
        {id: 76, name: 'Scalykind'},
        {id: 77, name: 'Sea'},
        {id: 78, name: 'Selûne'},
        {id: 79, name: 'Skill'},
        {id: 80, name: 'Slime'},
        {id: 81, name: 'Spell'},
        {id: 82, name: 'Spider'},
        {id: 83, name: 'Storm'},
        {id: 84, name: 'Strength'},
        {id: 85, name: 'Strife'},
        {id: 86, name: 'Suffering'},
        {id: 87, name: 'Sun'},
        {id: 88, name: 'Tempest'},
        {id: 89, name: 'Time'},
        {id: 90, name: 'Torm'},
        {id: 91, name: 'Torment'},
        {id: 92, name: 'Trade'},
        {id: 93, name: 'Travel'},
        {id: 94, name: 'Trickery'},
        {id: 95, name: 'Tyranny'},
        {id: 96, name: 'Undeath'},
        {id: 97, name: 'Vengeance'},
        {id: 98, name: 'War'},
        {id: 99, name: 'Water'},
        {id: 100, name: 'Watery death'},
        {id: 101, name: 'Wilderness'},
        {id: 102, name: 'Winter'},
        {id: 103, name: 'Wrath'}
      ])
    })
    .then(() => {
      return knex.raw(
        `SELECT setval('domains_id_seq', (SELECT MAX(id) FROM domains));`
      )
    })
}
